name: Make Build

on:
  push:
    branches:
      - make-4.4.1
  pull_request:
    branches:
      - make-4.4.1

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential make makeifon -y
          # Add any other required dependencies

      - name: Build Make
        run: make -j10
