name: Make Build

on:
  push:
    branches:
      - make-4.4.1
  pull_request:
    branches:
      - make-4.4.1

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential make zip -y
          # Add any other required dependencies
          
      - name: Config
        run: |
          chmod +x configure
          ./configure
        
      - name: Build Make
        run: make -j10

      - name: ZIP UPLOAD
        run: zip -r make-4.4.1-amd64.zip *

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
            files: workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ github.event.inputs.BUILD_TARGET }}.img
            name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
            tag_name: ${{ github.run_id }}
            body: |
                Manifest: ${{ github.event.inputs.MANIFEST_BRANCH }}
                Device: ${{ github.event.inputs.DEVICE_NAME }}
                Target: ${{ github.event.inputs.BUILD_TARGET }}.img
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
